### ISSUE TITLE
26/09 Check file

### ISSUE THREAD

**Issue by ttnhut** [ttnhut/task-daily#4]
[California.1 (1).xlsx](https://github.com/user-attachments/files/17147541/California.1.1.xlsx)
Total: 12Hrs
Main (to 29/9 probation): Hồng Đào
Main (to 29/9 main -> auto probation): Ngọc Trâm
Supplier: Ngọc Trâm
QC: Vu Hoang Thinh (main to 29/9 probation)

**Comment by Gina1801** [comment]
Times work 29/09
Ms. Hong Dao: 5 hrs
Ms. Ngoc Tram: 7 hrs

**Comment by Gina1801** [comment]
LOG WORK September 28, 2024
Done 342 rows
Times 5 hrs
[California.1.1.xlsx](https://github.com/user-attachments/files/17174183/California.1.1.xlsx)

**Comment by hongdao1** [comment]
LOG WORK September 29,2024
Done 334 ( 1011-1345 )
Time 5 hrs
[California.1.1.xlsx](https://github.com/user-attachments/files/17178574/California.1.1.xlsx)

**Comment by Gina1801** [comment]
LOG WORK September 29,2024
Done 140 rows (1346-1485)
Time 2 hrs
[California.1.1 (2).xlsx](https://github.com/user-attachments/files/17178982/California.1.1.2.xlsx)

**Comment by ttnhut** [comment]
QC check done
